### ISSUE TITLE
Integration stalls if Word is located in a directory with "&" symbols.

### ISSUE THREAD

**Issue by Tophernad** [zotero/zotero-word-for-mac-integration#12]
Hello,

When I use Zotero with Microsoft Office 2016, it either stalls Word or says that Zotero can't be found. I found that the issue was related to where I keep Word 2016. I put all my Office locations in another folder called "Office & Productivity". Zotero only looks for Word 2016 in /Applications and /Applications/Microsoft Office 2016. Is there a way to select a different directory to look in or preference file to configure? I found where to add additional locations but I'm getting build errors with Xcode. 

Zotero gives me this error when I try to install my version of the "libzoteroMacWordIntegration.dylib"

`[Exception... "*** -[NSFileManager fileSystemRepresentationWithPath:]: nil or empty path argument @[install:install.m:194]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: file:///Applications/Zotero.app/Contents/Resources/extensions/zoteroMacWordIntegration@zotero.org/components/zoteroMacWordIntegration.js :: checkStatus :: line 211"  data: no]`

Thanks,

Topher Nadauld

**Comment by adomasven** [comment]
This is actually a consequence of having "&" in your path, which is not properly escaped [here](https://github.com/zotero/zotero-word-for-mac-integration/blob/master/build/template/Zotero.dotm/word/vbaProject.bin/Zotero.bas#L67):

```
quoted form of POSIX path of (path to current application)
```

**Comment by Tophernad** [comment]
Thanks for finding the issue. It works if I don't have the "&" in the path. When do you think there will be a fix for the error?

**Comment by Tophernad** [comment]
Hello! 
I noticed that there was a new version of Zotero released. The new release still requires that I change the directory with the "&" to "and". Is there still a fix coming out for that error?
Thanks!

**Comment by Tophernad** [comment]
@adomasven A new version of Zotero came out and the issue is still present. What version do you think we would be able to see a fix for it?
Thanks!

**Comment by adomasven** [comment]
@Tophernad Could you install the [Zotero Beta](https://www.zotero.org/support/dev_builds), reinstall the plugin from Preferences -> Cite -> Word Processors and test if you can still reproduce this?

**Comment by Tophernad** [comment]
Thanks Adomas! It worked. I was able to add a citation.

Thanks,

Topher Nadauld
Client Platform Services - Mac
topher.nadauld@utah.edu<mailto:topher.nadauld@utah.edu>

On Apr 23, 2018, at 1:24 AM, Adomas Ven <notifications@github.com<mailto:notifications@github.com>> wrote:


@Tophernad<https://github.com/Tophernad> Could you install the Zotero Beta<https://www.zotero.org/support/dev_builds>, reinstall the plugin from Preferences -> Cite -> Word Processors and test if you can still reproduce this?
