### ISSUE TITLE
Update references to Zotero Standalone and Firefox

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-word-for-mac-integration#15]
e.g., "Word could not communicate with Zotero. Please ensure that Zotero Standalone or Firefox is open and try again."

**Comment by adomasven** [comment]
Already done https://github.com/zotero/zotero-word-for-mac-integration/commit/601cb9ea429dc1b20812b8ab8ca73c81c4743f38

**Comment by dstillman** [comment]
https://github.com/zotero/zotero-word-for-mac-integration/blob/ff5e8c69b1158fd40ea21e109927f087796514a2/build/src/install.m#L456

https://github.com/zotero/zotero-word-for-mac-integration/blob/81ef6a0b12ed28ba1c02901229859dee8dbcb13a/build/template/Zotero.dot/Zotero.bas#L45
