### ISSUE TITLE
Better error message if user denies Word control for Zotero

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-word-for-mac-integration#20]
See https://forums.zotero.org/discussion/73896/zotero-integration-error

**Comment by dstillman** [comment]
Do we have any way of checking whether we have access without triggering the prompt (and of distinguishing that from the case of access already having been denied)? If so, it would be good to pop up a dialog before the prompt appears warning people that they're about to get a message about Terminal and telling them that they should accept it.

**Comment by adomasven** [comment]
> Do we have any way of checking whether we have access without triggering the prompt (and of distinguishing that from the case of access already having been denied)? If so, it would be good to pop up a dialog before the prompt appears warning people that they're about to get a message about Terminal and telling them that they should accept it.

Yes, we can do this.
