### ISSUE TITLE
Zotero 7 not prompting to control Word

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-word-for-mac-integration#34]
Following up on https://github.com/zotero/zotero-word-for-mac-integration/issues/33#issuecomment-1560590899, I'm finding that Zotero 7 doesn't properly trigger the permissions prompt.

If I do `tccutil reset AppleEvents org.zotero.zotero-beta`, run Zotero 7, and click Add/Edit Citation, I get our dialog about missing permissions. If I then run Zotero 6 beta and click Add/Edit Citation, I get the prompt for Word, and then if I switch back to Zotero 7 it continues to work. So somehow we seem to be throwing the dialog about missing permissions without properly triggering the permissions request.

Last night, before #33 was fixed, along with our generic error dialog I was seeing Zotero 7 trigger a prompt for System Events — not sure sure if that's some fallback or other action we trigger (`activate`?) if the main request fails. With the permission granted by Zotero 6, I'm not seeing any prompt for System Events in Z7.

**Comment by adomasven** [comment]
Oh, my bad. It doesn't work still. I was accidentally running the Zotero 6 from `/Applications/` by not providing the full path to `open` initially
