### ISSUE TITLE
Support Office 2016

### ISSUE THREAD

**Issue by simonster** [zotero/zotero-word-for-mac-integration#6]
The code itself appears to work with Office 2016, but the following issues make it unusable in practice:

* [x] The toolbar doesn't appear even if the Startup folder is specified and there is no script menu (now fixed by MS)
* [ ] Inserting RTF requires granting access to the temporary file (due to sandboxing)
* [ ] Sandboxing prevents us from communicating directly with Zotero from within Word

**Comment by Ervinliz1** [comment]
I'm not as techy but I believe this solution can be implemented in the mean time http://wp.me/p5M5Kz-2E
Hope it helps!

**Comment by dstillman** [comment]
@Ervinliz1: This tracker is for developer use only. Please post to the forums for non-technical discussion. (Also, most people are aware of the other ways to generate bibliographies in Zotero. As Aurimas responded to you in the forums, it doesn't provide equivalent functionality.)

**Comment by jonathanmorgan** [comment]
If this is something that you have some understanding of such that you could point me to the things I'd need to understand to help, I'd be willing to look into options and try to help with this.  If work is already in progress and it would be more work than help, at the least, I'd be willing to test once you get to that point.

**Comment by simonster** [comment]
For posterity, Microsoft fixed the toolbar issue, and we work around the latter two issues by putting everything within the appropriate sandboxed directories.
